#!/usr/bin/env node
/**
 * Generate every packaging target from skills/<name>/SKILL.md.
 *
 *   node scripts/package.mjs            write the generated files
 *   node scripts/package.mjs --check    exit 1 if any generated file is stale
 *
 * SKILL.md is the only hand-maintained source. Three targets are derived from
 * it: GitHub Copilot custom agents, the Claude Code plugin manifest, and the
 * Cursor plugin manifest. The --check mode runs in CI so the three can never
 * drift apart from the source or from each other.
 */

import { readFileSync, writeFileSync, readdirSync, mkdirSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const SKILLS_DIR = join(ROOT, "skills");

// Package-level facts that are not owned by any single skill. The version is
// not duplicated here -- it is read from the manifest below.
const PACKAGE = {
  name: "dataforge",
  displayName: "Dataforge",
  description:
    "Universal data platform skill framework for metric pipeline engineering, data exploration, and deployment orchestration.",
  license: "MIT",
  keywords: [
    "dataforge",
    "data-platform",
    "metrics",
    "pipelines",
    "analytics",
    "duckdb",
    "databricks",
  ],
};

const GENERATED_NOTICE =
  "Generated by scripts/package.mjs from skills/%s/SKILL.md. Do not edit by hand.";

/**
 * Parse the subset of YAML the skill frontmatter actually uses: scalars,
 * folded block scalars (`>-`), one level of nesting, and flow sequences.
 * A full YAML parser would be a dependency for no benefit.
 */
function parseFrontmatter(text) {
  const match = text.match(/^---\n([\s\S]*?)\n---\n/);
  if (!match) throw new Error("missing frontmatter");
  const body = text.slice(match[0].length);
  const lines = match[1].split("\n");
  const result = {};
  let current = result;
  let folding = null;

  for (const line of lines) {
    if (folding) {
      if (/^\s{2,}\S/.test(line) && !/^\s{2,}[\w-]+:/.test(line.slice(folding.indent))) {
        folding.parts.push(line.trim());
        continue;
      }
      folding.target[folding.key] = folding.parts.join(" ");
      folding = null;
    }
    if (!line.trim() || line.trimStart().startsWith("#")) continue;

    const indent = line.length - line.trimStart().length;
    const kv = line.trim().match(/^([\w-]+):\s*(.*)$/);
    if (!kv) continue;
    const [, key, rawValue] = kv;
    current = indent === 0 ? result : result[Object.keys(result).pop()];

    if (rawValue === ">-" || rawValue === ">") {
      folding = { target: current, key, parts: [], indent };
    } else if (rawValue === "") {
      current[key] = {};
    } else if (rawValue.startsWith("[")) {
      current[key] = rawValue
        .slice(1, -1)
        .split(",")
        .map((v) => v.trim().replace(/^["']|["']$/g, ""))
        .filter(Boolean);
    } else {
      current[key] = rawValue.replace(/^["']|["']$/g, "");
    }
  }
  if (folding) folding.target[folding.key] = folding.parts.join(" ");
  return { frontmatter: result, body };
}

function readSkills() {
  return readdirSync(SKILLS_DIR, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .sort()
    .map((name) => {
      const path = join(SKILLS_DIR, name, "SKILL.md");
      const { frontmatter, body } = parseFrontmatter(readFileSync(path, "utf8"));
      if (frontmatter.name !== name) {
        throw new Error(`${path}: frontmatter name "${frontmatter.name}" != directory "${name}"`);
      }
      return { name, frontmatter, body };
    });
}

/** Single source of truth for the release version. */
function readVersion() {
  const manifest = readFileSync(join(ROOT, "assets", "dataforge.manifest.seed.example.yaml"), "utf8");
  const match = manifest.match(/^skill_version:\s*"([^"]+)"/m);
  if (!match) throw new Error("skill_version not found in the seed example manifest");
  return match[1];
}

/** Collapse `.` and `..` segments without touching the filesystem. */
function posixNormalize(path) {
  const out = [];
  for (const segment of path.split("/")) {
    if (segment === "." || segment === "") continue;
    if (segment === ".." && out.length && out.at(-1) !== "..") out.pop();
    else out.push(segment);
  }
  return out.join("/");
}

/**
 * Rewrite links that are relative to the skill directory so they resolve from
 * the repository root, which is where a Copilot agent file is read from.
 */
function rehomeLinks(body, name) {
  return body.replace(/\]\((?!https?:|#|\/)([^)]+)\)/g, (whole, target) => {
    const [path, anchor = ""] = target.split(/(#.*)$/);
    return `](${posixNormalize(`skills/${name}/${path}`)}${anchor})`;
  });
}

function copilotAgent({ name, frontmatter, body }) {
  const tools = frontmatter.metadata?.["agent-tools"] ?? ["read", "search"];
  return [
    "---",
    `name: ${name}`,
    `description: ${JSON.stringify(frontmatter.description)}`,
    `tools: [${tools.join(", ")}]`,
    "---",
    "",
    `<!-- ${GENERATED_NOTICE.replace("%s", name)} -->`,
    "",
    rehomeLinks(body, name).trim(),
    "",
  ].join("\n");
}

function pluginManifest(version, { skills, hooks }) {
  return JSON.stringify({ ...PACKAGE, version, skills, hooks }, null, 2) + "\n";
}

function build() {
  const skills = readSkills();
  const version = readVersion();
  const outputs = new Map();

  for (const skill of skills) {
    outputs.set(join(".github", "agents", `${skill.name}.agent.md`), copilotAgent(skill));
  }
  outputs.set(
    join(".claude-plugin", "plugin.json"),
    pluginManifest(version, { skills: "./skills", hooks: "./hooks/claude.json" }),
  );
  outputs.set(
    join(".cursor-plugin", "plugin.json"),
    pluginManifest(version, { skills: "skills", hooks: "hooks/cursor.json" }),
  );
  return outputs;
}

function main() {
  const check = process.argv.includes("--check");
  const outputs = build();
  const stale = [];

  for (const [relative, contents] of outputs) {
    const path = join(ROOT, relative);
    const existing = existsSync(path) ? readFileSync(path, "utf8") : null;
    if (existing === contents) continue;
    if (check) {
      stale.push(`${relative} (${existing === null ? "missing" : "out of date"})`);
      continue;
    }
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, contents);
    console.log(`wrote ${relative}`);
  }

  if (check) {
    if (stale.length) {
      console.error("Generated packaging targets are stale:");
      for (const entry of stale) console.error(`  ${entry}`);
      console.error("\nRun `node scripts/package.mjs` and commit the result.");
      process.exit(1);
    }
    console.log(`${outputs.size} packaging targets are up to date.`);
  }
}

main();
